### ISSUE TITLE
Supportive Documents

### ISSUE THREAD

**Issue by lamplus** [on-site/grantzilla#302]
Add checkboxes for each documents.

**Comment by scottjones** [comment]
@joedean How do I make uploads work on development?

**Comment by scottjones** [comment]
![image](https://cloud.githubusercontent.com/assets/444693/21592085/faf57318-d0cf-11e6-9a10-aa7dcd29c12e.png)
I'm planning to make it so that we select the category for the upload, and then we can begin checking things off once they've been uploaded.

**Comment by betesh** [comment]
@scottjones uploads should work out of the box in development, but instead of uploading to S3, it uploads to a git-ignored directory inside your rails project: `Rails.root + "/public/system"`

**Comment by scottjones** [comment]
@betesh @joedean I'm getting this error from `config/initializers/paperclip.rb:17`: 

```
Paperclip::Attachment::InsecureUrlError at /uploads`:  Use `expiring_url` instead of
`url`.  In production, attachments are stored on S3 and are not accessible to the
public except through expiring URL's. For example, `expiring_url(10, default_style)`
returns a URL that is valid for only 10 seconds, just long enough for it to open
in the browser.
```

What am I supposed to be doing here?

**Comment by betesh** [comment]
Use the `expring_url` method instead of the `url` method as the error message says.  The first arg is a number of seconds until it expires, default 3600.  The 2nd arg is a style, and I don't think we define any custom ones in this project, so just leave it blank.

**Comment by scottjones** [comment]
@joedean @betesh This is happening on the call to `@upload.save` in `uploads_controller`.  I'm just trying to figure out how to use the code that's already here...  I don't see any calls to `url`.  Someone must have had this work in development?  Does it make more sense for the `url` monkeypatch in the initializer to call the `expiring_url` and log a warning of some kind?

**Comment by betesh** [comment]
Nope, it doesn't make sense to log a warning.  If you use the url method, it's guaranteed to be a bug in production.

**Comment by betesh** [comment]
Can you show us a stacktrace?

**Comment by scottjones** [comment]
```
Paperclip::Attachment::InsecureUrlError - Use `expiring_url` instead of `url`.  In production, attachments are stored on S3 and are not accessible to the public except through expiring URL's. For example, `expiring_url(10, default_style)` returns a URL that is valid for only 10 seconds, just long enough for it to open in the browser.:
  config/initializers/paperclip.rb:17:in `url'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/interpolations.rb:59:in `url'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/interpolations.rb:35:in `block (2 levels) in interpolate'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/interpolations.rb:35:in `block in interpolate'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/interpolations.rb:34:in `interpolate'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/attachment.rb:547:in `interpolate'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/attachment.rb:169:in `path'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/storage/filesystem.rb:38:in `block in flush_writes'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/storage/filesystem.rb:37:in `flush_writes'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/attachment.rb:241:in `save'
   () Users/scott/.rvm/gems/ruby-2.3.0/bundler/gems/paperclip-fbbba2802e22/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:396:in `block in make_lambda'
  activesupport (5.0.0) lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
  activesupport (5.0.0) lib/active_support/callbacks.rb:456:in `block in call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:456:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
  activerecord (5.0.0) lib/active_record/callbacks.rb:298:in `create_or_update'
  activerecord (5.0.0) lib/active_record/persistence.rb:125:in `save'
  activerecord (5.0.0) lib/active_record/validations.rb:44:in `save'
  activerecord (5.0.0) lib/active_record/attribute_methods/dirty.rb:22:in `save'
  activerecord (5.0.0) lib/active_record/transactions.rb:319:in `block (2 levels) in save'
  activerecord (5.0.0) lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
  activerecord (5.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
  activerecord (5.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
  activerecord (5.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
  activerecord (5.0.0) lib/active_record/transactions.rb:211:in `transaction'
  activerecord (5.0.0) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
  activerecord (5.0.0) lib/active_record/transactions.rb:319:in `block in save'
  activerecord (5.0.0) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
  activerecord (5.0.0) lib/active_record/transactions.rb:318:in `save'
  activerecord (5.0.0) lib/active_record/suppressor.rb:41:in `save'
  app/controllers/uploads_controller.rb:12:in `create'
  actionpack (5.0.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0) lib/abstract_controller/base.rb:188:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.0.0) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  activesupport (5.0.0) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0) lib/abstract_controller/base.rb:126:in `process'
  actionview (5.0.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.0) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.0) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
  rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
  activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  railties (5.0.0) lib/rails/engine.rb:522:in `call'
  puma (3.4.0) lib/puma/configuration.rb:224:in `call'
  puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
  puma (3.4.0) lib/puma/server.rb:406:in `process_client'
  puma (3.4.0) lib/puma/server.rb:271:in `block in run'
  puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by betesh** [comment]
https://github.com/on-site/grantzilla/pull/318 should fix this
